openapi: 3.0.1
info:
  title: DigitalProductionPlannerApi
  description: This is the OpenAPI Document on Azure Functions
  version: '1.0'
servers:
- url: https://esl.caseys.io/digitalproductionplannerapi
paths:
  /graphql:
    post:
      tags:
      - GraphQL
      summary: GraphQL endpoint for production planner data.
      description: Executes GraphQL operations for production planner data.
      operationId: graphql
      requestBody:
        description: The query to execute against the graph for data.
        content:
          application/json:
            schema:
              type: string
            example: string
      responses:
        '200':
          description: The production planner data returned from the executed graph query.
          content:
            application/json:
              schema:
                type: string
              example: string
  /openapi/v3.json:
    get:
      summary: Get OpenApi Specification
      description: Gets the OpenApi specification in . format with the parameters .
      operationId: getOpenApiSpec
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
- apiKeyHeader: []
- apiKeyQuery: []
